//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resources.rc
//
#define IDI_ICQ                         101
#define IDS_IDENTIFY                    102
#define IDD_ICQACCOUNT                  103
#define IDD_ASKAUTH                     104
#define IDD_LOGINPW                     105
#define IDD_OPT_ICQ                     108
#define IDD_OPT_ICQCONTACTS             109
#define IDD_OPT_ICQFEATURES             110
#define IDD_OPT_ICQPRIVACY              111
#define IDD_INFO_ICQ                    112
#define IDD_INFO_ICQ_CLIENT             113
#define IDD_INFO_CHANGEINFO             114
#define IDD_ICQADVANCEDSEARCH           115
#define IDD_ICQUPLOADLIST               116
#define IDD_SETXSTATUS                  117
#define IDD_PWCONFIRM                   118
#define IDD_OPT_POPUPS                  119
#define IDD_OPT_POPUPS_MORE             120
#define IDD_OPT_ICQCLIENTID             121
#define IDI_ADVANCED_FEATURES           121
#define IDD_OPT_ICQEVENTSLOG            122
#define IDI_CHECKED                     122
#define IDD_OPT_ICQFEATURESADV          123
#define IDI_UNCHECKED                   123
#define IDD_SENDTZER                    124
#define IDI_DC                          124
#define IDD_ICQREGUIN                   125
#define IDI_HIDDEN                      125
#define IDD_ASD_OPTIONS                 126
#define IDI_INCOGNITO                   126
#define IDD_CAPS_LIST                   127
#define IDI_VISIBLE                     127
#define IDD_SRVS_LIST                   128
#define IDI_INVISIBLE                   128
#define IDI_SCAN                        129
#define IDI_SCAN_START                  130
#define IDI_SCAN_STOP                   131
#define IDI_SCAN_PAUSE                  132
#define IDI_SERVLIST                    133
#define IDI_AUTH_ASK                    150
#define IDI_AUTH_GRANT                  151
#define IDI_AUTH_REVOKE                 152
#define IDI_SERVLIST_ADD                160
#define IDI_TZER                        180
#define IDI_XSTATUS0                    200
#define IDI_XSTATUS1                    201
#define IDI_XSTATUS2                    202
#define IDI_XSTATUS3                    203
#define IDI_XSTATUS4                    204
#define IDI_XSTATUS5                    205
#define IDI_XSTATUS6                    206
#define IDI_XSTATUS7                    207
#define IDI_XSTATUS8                    208
#define IDI_XSTATUS9                    209
#define IDI_XSTATUS10                   210
#define IDI_XSTATUS11                   211
#define IDI_XSTATUS12                   212
#define IDI_XSTATUS13                   213
#define IDI_XSTATUS14                   214
#define IDI_XSTATUS15                   215
#define IDI_XSTATUS16                   216
#define IDI_XSTATUS17                   217
#define IDI_XSTATUS18                   218
#define IDI_XSTATUS19                   219
#define IDI_XSTATUS20                   220
#define IDI_XSTATUS21                   221
#define IDI_XSTATUS22                   222
#define IDI_XSTATUS23                   223
#define IDI_XSTATUS24                   224
#define IDI_XSTATUS25                   225
#define IDI_XSTATUS26                   226
#define IDI_XSTATUS27                   227
#define IDI_XSTATUS28                   228
#define IDI_XSTATUS29                   229
#define IDI_XSTATUS30                   230
#define IDI_XSTATUS31                   231
#define IDI_XSTATUS32                   232
#define IDI_XSTATUS33                   233
#define IDI_XSTATUS34                   234
#define IDI_XSTATUS35                   235
#define IDI_XSTATUS36                   236
#define IDI_XSTATUS37                   237
#define IDI_QIPSTATUS1                  251
#define IDI_QIPSTATUS2                  252
#define IDI_QIPSTATUS3                  253
#define IDI_QIPSTATUS4                  254
#define IDI_QIPSTATUS5                  255
#define IDI_TZER1                       271
#define IDI_TZER2                       272
#define IDI_TZER3                       273
#define IDI_TZER4                       274
#define IDI_TZER5                       275
#define IDI_TZER6                       276
#define IDI_TZER7                       277
#define IDI_TZER8                       278
#define IDI_TZER9                       279
#define IDI_TZER10                      270
#define IDI_TZER11                      271
#define IDI_TZER12                      272
#define IDI_EXPANDSTRINGEDIT            300
#define IDC_POPUPS_ENABLED              410
#define IDC_POPUPS_LOG_ENABLED          411
#define IDC_POPUPS_SPAM_ENABLED         412
#define IDC_POPUP_LOG0_TEXTCOLOR        420
#define IDC_POPUP_LOG1_TEXTCOLOR        421
#define IDC_POPUP_LOG2_TEXTCOLOR        422
#define IDC_POPUP_LOG3_TEXTCOLOR        423
#define IDC_POPUP_SPAM_TEXTCOLOR        425
#define IDC_POPUP_UNKNOWN_TEXTCOLOR     426
#define IDC_POPUP_FOUND_TEXTCOLOR       427
#define IDC_POPUP_SCAN_TEXTCOLOR        428
#define IDC_POPUP_VISIBILITY_TEXTCOLOR  429
#define IDC_POPUP_LOG0_BACKCOLOR        430
#define IDC_POPUP_CLIENTCHANGE_TEXTCOLOR 430
#define IDC_POPUP_LOG1_BACKCOLOR        431
#define IDC_POPUP_INFOREQUEST_TEXTCOLOR 431
#define IDC_POPUP_LOG2_BACKCOLOR        432
#define IDC_POPUP_IGNORECHECK_TEXTCOLOR 432
#define IDC_POPUP_LOG3_BACKCOLOR        433
#define IDC_POPUP_SELFREMOVE_TEXTCOLOR  433
#define IDC_POPUP_AUTH_TEXTCOLOR        434
#define IDC_POPUP_SPAM_BACKCOLOR        435
#define IDC_POPUP_UNKNOWN_BACKCOLOR     436
#define IDC_POPUP_FOUND_BACKCOLOR       437
#define IDC_POPUP_SCAN_BACKCOLOR        438
#define IDC_POPUP_VISIBILITY_BACKCOLOR  439
#define IDC_POPUP_LOG0_TIMEOUT          440
#define IDC_POPUP_CLIENTCHANGE_BACKCOLOR 440
#define IDC_POPUP_LOG1_TIMEOUT          441
#define IDC_POPUP_INFOREQUEST_BACKCOLOR 441
#define IDC_POPUP_LOG2_TIMEOUT          442
#define IDC_POPUP_IGNORECHECK_BACKCOLOR 442
#define IDC_POPUP_LOG3_TIMEOUT          443
#define IDC_POPUP_SELFREMOVE_BACKCOLOR  443
#define IDC_POPUP_SPAM_TIMEOUT          444
#define IDC_POPUP_UNKNOWN_TIMEOUT       445
#define IDC_POPUP_FOUND_TIMEOUT         446
#define IDC_POPUP_SCAN_TIMEOUT          447
#define IDC_POPUP_VISIBILITY_TIMEOUT    448
#define IDC_POPUP_CLIENTCHANGE_TIMEOUT  449
#define IDC_USEWINCOLORS                450
#define IDC_POPUP_INFOREQUEST_TIMEOUT   450
#define IDC_USESYSICONS                 451
#define IDC_POPUP_IGNORECHECK_TIMEOUT   451
#define IDC_POPUP_SELFREMOVE_TIMEOUT    452
#define IDC_POPUP_AUTH_BACKCOLOR        453
#define IDC_POPUP_AUTH_TIMEOUT          454
#define IDC_PREVIEW                     455
#define IDC_POPUP_XUPDATER_BACKCOLOR    456
#define IDC_POPUP_XUPDATER_TEXTCOLOR    457
#define IDC_POPUP_XUPDATER_TIMEOUT      458
#define IDC_LOG                         1001
#define IDC_SAVEPASS                    1004
#define IDC_RETRXSTATUS                 1005
#define IDC_SSL                         1008
#define IDC_MD5LOGIN                    1009
#define IDC_UTFENABLE                   1010
#define IDC_XTITLE                      1010
#define IDC_KEEPALIVE                   1011
#define IDC_XMSG                        1011
#define IDC_UTFALL                      1012
#define IDC_UTFSTATIC                   1013
#define IDC_UTFCODEPAGE                 1014
#define IDC_PW                          1015
#define IDC_TEMPVISIBLE                 1015
#define IDC_REGISTER                    1016
#define IDC_EDITAUTH                    1017
#define IDC_RETRIEVE_LOST               1017
#define IDC_LOGINPW                     1018
#define IDC_INSTRUCTION                 1019
#define IDC_PASSWORD                    1020
#define IDC_SUPTIME                     1020
#define IDC_DCENABLE                    1020
#define IDC_DCPASSIVE                   1021
#define IDC_OLDPASS                     1021
#define IDC_ICQNUM                      1022
#define IDC_DCICON                      1022
#define IDC_RETRIEVE                    1024
#define IDC_POPUP_SPAM_ENABLED          1026
#define IDC_POPUPS_UIN_ENABLED          1027
#define IDC_POPUP_UNKNOWN_ENABLED       1027
#define IDC_CHANGEID                    1027
#define IDC_POPUPS_SHOW_FOR_HIDDEN_ENABLED 1028
#define IDC_POPUP_FOUND_ENABLED         1028
#define IDC_IDSTATIC                    1028
#define IDADD                           1028
#define IDC_POPUPS_SHOW_FOR_IGNORED_ENABLED 1029
#define IDC_POPUP_SCAN_ENABLED          1029
#define IDC_SHOWREALID                  1029
#define IDDEL                           1029
#define IDC_AIMENABLE                   1030
#define IDC_POPUPS_SHOW_FOR_NOTONLIST_ENABLED 1030
#define IDC_POPUP_VISIBILITY_ENABLED    1030
#define IDC_GETSTATUS                   1030
#define IDEDIT                          1030
#define IDC_POPUP_CLIENTCHANGE_ENABLED  1031
#define IDC_TITLEICON                   1031
#define IDCCLOSE                        1031
#define IDC_PICTURE                     1032
#define IDC_POPUP_INFOREQUEST_ENABLED   1032
#define IDC_ASDOPTIONS                  1032
#define IDC_CAPSBOX                     1032
#define IDC_FORCEREFRESH                1032
#define IDC_SERVERS                     1032
#define IDC_REGUIN                      1033
#define IDC_POPUP_IGNORECHECK_ENABLED   1033
#define IDC_EDIT_SERVER                 1033
#define IDC_POPUP_SELFREMOVE_ENABLED    1034
#define IDC_VERSION_CHECKBOX            1034
#define IDC_EDIT_PORT                   1034
#define IDC_CLIST                       1035
#define IDC_POPUP_AUTH_ENABLED          1035
#define IDC_SET_VERSION_RANGE           1035
#define IDC_POPUP_XUPDATER_ENABLED      1036
#define IDC_KILLUNKNOWN                 1038
#define IDC_XSTATUSENABLE               1040
#define IDC_XSTATUSAUTO                 1041
#define IDC_XSTATUSRESET                1042
#define IDC_TZER                        1043
#define IDC_LOG_REMOVE_HISTORY          1043
#define IDC_DETECT_VIA_STATUS_MESSAGE   1043
#define IDC_AUTOCHANGE                  1043
#define IDC_ADDTEMP                     1043
#define IDC_RTF                         1043
#define IDC_USERCHKPOS                  1044
#define IDC_CUSTOM_CAP                  1044
#define IDC_DETECT_VIA_XTRAZ            1044
#define IDC_TMPSNDADDED                 1044
#define IDC_KILLSPAMBOTS                1045
#define IDC_DETECT_VIA_URL              1045
#define IDC_TMPREQAUTH                  1045
#define IDC_CLIENTCAPS                  1045
#define IDC_CAPABILITIES                1045
#define IDC_DETECT_UNAUTHORIZED         1046
#define IDC_REMOVE_TEMP                 1046
#define IDC_CLIENTICON                  1046
#define IDC_REMOVETEMP                  1046
#define IDC_DETECT_VIA_AUTH             1047
#define IDC_EMAIL                       1048
#define IDC_ICON_POS_TEXT               1048
#define IDC_PICTURE_CONTENT             1049
#define IDC_NEWUIN_PASS                 1051
#define IDC_NICK                        1053
#define IDC_NEWUININFO                  1053
#define IDC_UIN_IMAGE                   1054
#define IDC_REPLACEXTEXT                1055
#define IDC_NEEDRESTART                 1056
#define IDC_SET_VERSION                 1057
#define IDC_FORCEXSTATUS                1057
#define IDC_GENDER                      1060
#define IDC_CITY                        1061
#define IDC_STATE                       1062
#define IDC_COUNTRY                     1063
#define IDC_DELETE_TMP_CONTACTS         1064
#define IDC_ADD_TMP_CONTACTS            1065
#define IDC_COMPANY                     1066
#define IDC_TMP_CONTACTS_GROUP          1066
#define IDC_DEPARTMENT                  1067
#define IDC_SHOW_AUTH                   1067
#define IDC_LOG_IGNORECHECK_HISTORY     1067
#define IDC_ASD_FOR_OFFLINE             1067
#define IDC_XSTUPDATE                   1067
#define IDC_FILEPATH                    1068
#define IDC_XSTUPDATERATE               1068
#define IDC_CAPL_EDIT                   1068
#define IDC_POSITION                    1069
#define IDC_BROWSE                      1069
#define IDC_LOG_CHECKSTATUS_FILE        1070
#define IDC_LOG_CHECKSTATUS_HISTORY     1071
#define IDC_LOG_CLIENTCHANGE_FILE       1072
#define IDC_LOG_CLIENTCHANGE_HISTORY    1073
#define IDC_LOG_AUTH_FILE               1074
#define IDC_LOG_AUTH_HISTORY            1075
#define IDC_NOPSD_FOR_HIDDEN            1076
#define IDC_LOG_TO_CONTACTS_HISTORY     1076
#define IDC_XSTNONSTD                   1076
#define IDC_INCUSER                     1077
#define IDC_INCGLOBAL                   1078
#define IDC_FAKEWARNING                 1079
#define IDC_LOG_REQUEST_FILE            1080
#define IDC_LOG_INFOREQUEST_FILE        1080
#define IDC_LOG_REQUEST_HISTORY         1081
#define IDC_LOG_INFOREQUEST_HISTORY     1081
#define IDC_LOG_ASD_FILE                1082
#define IDC_LOG_ASD_HISTORY             1083
#define IDC_DC_ICON_POS_TEXT            1083
#define IDC_MODID_DESC                  1084
#define IDC_HTTPUSERAGENT               1084
#define IDC_MODID                       1085
#define IDC_INSTATUSMENU                1086
#define IDC_INMAINMENU                  1087
#define IDC_CAPL_ADD                    1090
#define IDC_CAPL_MODIFY                 1091
#define IDC_CAPL_DELETE                 1092
#define IDC_IP                          1094
#define IDC_UINSTATIC                   1122
#define IDC_UIN                         1123
#define IDC_STATIC11                    1154
#define IDC_STATIC12                    1155
#define IDC_ICQSERVER                   1171
#define IDC_ICQPORT                     1172
#define IDC_VERSION                     1179
#define IDC_XSTATUS_ICON_POS            1180
#define IDC_DC_ICON_POS                 1183
#define IDC_WHITERECT                   1220
#define IDC_FIRSTNAME                   1224
#define IDC_LASTNAME                    1225
#define IDC_REALIP                      1230
#define IDC_RECONNECTREQD               1239
#define IDC_OFFLINETOENABLE             1240
#define IDC_PORT                        1249
#define IDC_MIRVER                      1251
#define IDC_ONLINESINCE                 1252
#define IDC_SYSTEMUPTIME                1253
#define IDC_IDLETIME                    1254
#define IDC_STATUS                      1255
#define IDC_STATUS2                     1256
#define IDC_ADVSTATUS                   1256
#define IDC_SLOWSEND                    1301
#define IDC_ONLYSERVERACKS              1302
#define IDC_LOGLEVEL                    1331
#define IDC_LEVELDESCR                  1332
#define IDC_NOERRMULTI                  1333
#define IDC_STICQGROUP                  1374
#define IDC_ASD                         1380
#define IDC_XSTATUSICON                 1381
#define IDC_NOASD                       1383
#define IDC_PSD                         1384
#define IDC_LOG_REMOVE_FILE             1385
#define IDC_LOG_IGNORECHECK_FILE        1387
#define IDC_ASDSTARTUP                  1389
#define IDC_AGERANGE                    1410
#define IDC_MARITALSTATUS               1411
#define IDC_KEYWORDS                    1412
#define IDC_LANGUAGE                    1414
#define IDC_WORKFIELD                   1421
#define IDC_PASTCAT                     1422
#define IDC_PASTKEY                     1423
#define IDC_INTERESTSCAT                1424
#define IDC_INTERESTSKEY                1425
#define IDC_ORGANISATION                1426
#define IDC_ORGKEYWORDS                 1427
#define IDC_OTHERGROUP                  1429
#define IDC_ONLINEONLY                  1430
#define IDC_HOMEPAGECAT                 1431
#define IDC_HOMEPAGEKEY                 1432
#define IDC_SUMMARYGROUP                1434
#define IDC_WORKGROUP                   1435
#define IDC_LOCATIONGROUP               1436
#define IDC_BACKGROUNDGROUP             1437
#define IDC_NEWUINLINK                  1438
#define IDC_LOOKUPLINK                  1439
#define IDC_RESETSERVER                 1472
#define IDC_SERVERBOX                   1473
#define IDC_UPLOADNOW                   1521
#define IDC_GROUPS                      1522
#define IDC_ALLGROUPS                   1526
#define IDC_VISIBILITY                  1527
#define IDC_IGNORE                      1528
#define IDC_ENABLE                      1529
#define IDC_LOADFROMSERVER              1530
#define IDC_BIGGERAVATARS               1531
#define IDC_ADDSERVER                   1532
#define IDC_SAVETOSERVER                1533
#define IDC_ENABLEAVATARS               1536
#define IDC_AUTOLOADAVATARS             1537
#define IDC_IGNORECHECK                 1537
#define IDC_STRICTAVATARCHECK           1539
#define IDC_WEBAWARE                    1546
#define IDC_DCALLOW_ANY                 1547
#define IDC_DCALLOW_CLIST               1548
#define IDC_DCALLOW_AUTH                1549
#define IDC_PUBLISHPRIMARY              1550
#define IDC_ADD_ANY                     1551
#define IDC_ADD_AUTH                    1552
#define IDC_STATUSMSG_CLIST             1553
#define IDC_STATUSMSG_VISIBLE           1554
#define IDC_STATIC_NOTONLINE            1555
#define IDC_STATIC_DC2                  1556
#define IDC_STATIC_DC1                  1557
#define IDC_STATIC_CLIST                1558
#define IDC_NOSTATUSREPLY               1559
#define IDC_SAVE                        1600
#define IDC_LIST                        1601
#define IDC_UPLOADING                   1602
#define IDC_TZER_RECIPIENT              1800
#define IDC_TZER_COMBO                  1801
#define IDC_TZER_EDIT                   1802
#define IDC_TITLE                       1803
#define IDC_DESC                        1804
#define IDC_ADVSTATUSICON               1809
#define IDC_ADVSTATUS_ICON_POS          1810
#define IDC_ADVSTATUS_ICON_POS_TEXT     1811
#define IDC_ADVSTATUSENABLE             1812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        301
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1813
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
